DATASET:
  NAME: mscoco
  TRAIN:
    PATTERN: tfrecords/train/*.tfrecord
    EXAMPLES: 149544
  VAL:
    PATTERN: tfrecords/val/*.tfrecord
    EXAMPLES: 6340
  COMMON:
    IMAGE_NORM: true
    MEANS: # imagenet means RGB
      - 0.485
      - 0.456
      - 0.406
    STDS:
      - 0.229
      - 0.224
      - 0.225
    INPUT_SHAPE:
      - 256
      - 192
      - 3
    K: 17
    SIGMA: 2.0

AUG:
  SCALE_FACTOR: 0.35
  ROT_PROB: 0.6
  ROT_FACTOR: 45
  FLIP_PROB: 0.5
  KP_FLIP: # coco
    - 0
    - 2
    - 1
    - 4
    - 3
    - 6
    - 5
    - 8
    - 7
    - 10
    - 9
    - 12
    - 11
    - 14
    - 13
    - 16
    - 15
  HALF_BODY_PROB: 0.3
  HALF_BODY_MIN_KP: 8
  KP_UPPER:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  ALBUM: false

MODEL:
  NAME: hrnet_w32

TRAIN:
  EPOCHS: 210
  LR: 0.001
  BATCH_SIZE: 32
  LR_FACTOR: 0.1
  LR_EPOCHS:
    - 170
    - 200

VAL:
  BATCH_SIZE: 48
  DO_EVAL: true
  COCO_JSON: datasets/mscoco/annotations/person_keypoints_val2017.json

WANDB:
  USE: true
  PROJECT: ssl-human-pose
  SUBTITLE: mscoco
  NAME: null

OUTPUT:
  DIR: null
  CKPT: null
